language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - cd example
  - pip install -r requirements/base.txt
  - ln -sf $(pwd)/../reversion/ $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")

# command to run tests
script:
   coverage run --omit */site-packages/*,*/migrations/*,*/lib/* manage.py test test_reversion.tests --settings=dj.settings.settings -v 2

addons:
  apt:
    packages:
    - xvfb
    - sqlite
    - libjpeg-dev
    - libpng-dev
    - gettext
